version: 2.1
setup: true
orbs:
  orb-tools: circleci/orb-tools@12.0
  shellcheck: circleci/shellcheck@3.1

filters: &filters
  tags:
    only: /.*/

workflows:
  test-deploy:
    jobs:
      - orb-tools/pack:
          filters: *filters
      # Publish a production version of the orb.
      - orb-tools/publish:
          orb_name: datadog/datadog-static-analyzer-circleci-orb
          vcs-type: << pipeline.project.type >>
          # Use a context to hold your publishing token.
          context: orb-publishing-static-analyzer
          pub-type: production
          enable-pr-comment: false
          requires:
            - orb-tools/pack
          # Run only for semantic tags
          # https://circleci.com/docs/workflows/#executing-workflows-for-a-git-tag
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/